[package]
name = "prime_printer"
version = "0.1.0"
authors = ["VoxWave <victor_bankowski@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.2"